- name: Prepare HELM env
  hosts: all
  collections:
   - community.general
  gather_facts: no

  tasks:
  - name: Create helm directory
    file:
      path: "/tmp/helm"
      state: directory
      mode: 0755
    tags:
    - init

  - name: Debug output
    debug:
      msg: "Hello"
